### ISSUE TITLE
Client Exception

### ISSUE THREAD

**Issue by Naskall** [berkayk/laravel-onesignal#77]
How can i fix this issue ?

Client error: `POST https://onesignal.com/api/v1/notifications` resulted in a `400 Bad Request` response:
{"errors":["app_id not found. You may be missing a Content-Type: application/json header."]}

best regards!

**Comment by Naskall** [comment]
Yes, now i have other issue, the player_id isnt in the mysql DB, i dont know how i make it works.

**Comment by IlhamWahabiGX** [comment]
@xcesaralejandro can you specifically say which is 'some files' that you mean? I think that can help another developer (include me)

**Comment by IlhamWahabiGX** [comment]
Ok, i got my solution

```php
php artisan config:clear
```
solve my problem

**Comment by xcesaralejandro** [comment]
@IlhamWahabiGX  I remember that I fixed that with:

`composer update`
`php artisan cache:clear`
`php artisan config:clear`

**Comment by Trexology** [comment]
I am also facing this issue, but clearing the cache does not fix it? Could this be a guzzle issue?

**Comment by intelligenceBabila** [comment]
Having this same issue. Have cleard cache nothing seems to work, verified if app_id is correct and it is. Verified if player id is sent properly and it is. So am confused right now. No added configuration, I setup the routnotificationonesignal. Function within the user model

**Comment by denisakira** [comment]
I'm also having a problem. I've used xdebug to see the flow of data and the app_id is set correctly, but it keeps resulting in:

https://onesignal.com/api/v1/notifications` resulted in a `400 Bad Request` response:
{"errors":["app_id not found. You may be missing a Content-Type: application/json header."]}
